import './globals.css'
// import Web3Providers from '@/app/components/Web3Providers';

export const metadata = {
  title: "Lucky Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Web3Providers> */}
          {children}
        {/* </Web3Providers> */}
      </body>
    </html>
  );
}
